apiVersion: apps/v1
kind: Deployment
metadata:
  name: facial-analysis-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: facial-analysis-app
  template:
    metadata:
      labels:
        app: facial-analysis-app
    spec:
      containers:
      - name: facial-analysis-container
        image: facial-analysis-app:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: facial-analysis-service
spec:
  selector:
    app: facial-analysis-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
